# Generated by Django 5.0.6 on 2024-06-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_checkoutinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutinfo',
            name='payment',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
