# Generated by Django 5.0.6 on 2024-07-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_checkoutinfo_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='username',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
